language: node_js
node_js:
- 8
- 10
script:
- npm run lint
- npm run travis.test
before_install:
- openssl aes-256-cbc -K $encrypted_e8aa77f7c9c5_key -iv $encrypted_e8aa77f7c9c5_iv
  -in db_config.js.enc -out db_config.js -d
